<?php
/**
 * Title: Software Product Page
 * Slug: cropx/page-software-product
 * Categories: cropx-pages
 * Inserter: true
 */
?>
<!-- wp:cropx/nav /-->
<!-- wp:cropx/hero-curved-standard {"eyebrow":"CropX System","heading":"Field Data Management","subheading":"CropX aggregates data from in and around the farm and transforms it into useful information to help farmers monitor the health of fields and crops. The information is easy to access and provides a holistic overview of field\u003cbr\u003econditions.","bgImageId":442,"bgImageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-agronomy-advisor-farmers-tablet.webp","bgFocalY":0.64,"phoneImageId":60,"phoneImageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/phone-mockup-b.webp","showCta":false,"showDeviceImage":false,"deviceScale":175,"deviceOffsetX":-58,"deviceOffsetY":14,"phoneScale":160,"phoneOffsetX":90,"phoneOffsetY":25} /-->
<!-- wp:cropx/three-column-icons {"heading":"Capabilities","backgroundVariant":"blue","columns":[{"icon":"fields","heading":"Manage all your farms, fields, and crops in one place","body":"The CropX platform aggregates data from across your entire operation in a single, customisable interface \u2014 with farm management tools to organise and schedule activities.","ctaLabel":"","ctaUrl":"#"},{"icon":"sensor-cloud","heading":"Make timely, data-driven agronomic decisions","body":"Insights and decision-support systems \u2014 covering disease risk, irrigation scheduling, and crop management \u2014 help your team act with confidence in real time.","ctaLabel":"","ctaUrl":"#"},{"icon":"antenna","heading":"Connect all your IoT devices, sensors, and farm machines","body":"The CropX system integrates with the equipment you already have \u2014 sensors, weather stations, irrigation controllers, and more \u2014 into one unified data layer.","ctaLabel":"","ctaUrl":"#"},{"icon":"fields","heading":"Make timely, data-driven agronomic decisions","body":"Insights and decision-support systems \u2014 covering disease risk, irrigation scheduling, and crop management \u2014 help your team act with confidence in real time.","ctaLabel":"","ctaUrl":"#"},{"icon":"fields","heading":"Manage all your farms, fields, and crops in one place","body":"The CropX platform aggregates data from across your entire operation in a single, customisable interface \u2014 with farm management tools to organise and schedule activities.","ctaLabel":"","ctaUrl":"#"}],"eyebrowColor":"white","showEyebrow":false,"showHeading":false} /-->
<!-- wp:cropx/two-column-overlay {"photoPosition":"left","heading":"Easily Manage Data","body":"Automatically import real-time data from soil sensors, satellites, farm \u003ca href=\u0022https://cropx.com/cropx-system/farm-data-connectivity/\u0022\u003emachinery\u003c/a\u003e, and other sources. This makes it easy to gather and manage all of your data.","photoId":429,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-agriculture-enterprise-tractor-pivots.webp","photoFocalY":0.41,"overlayId":42,"overlayUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/dashboard-spraying-conditions.webp","mobileStack":"text-first"} /-->
<!-- wp:cropx/two-column-overlay {"heading":"Quickly Find Information","body":"The Field Data function in the CropX platform offers you the possibility to review and compare data along with crop performance. All of the information you need about a field is at your fingertips.","photoId":437,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-agronomist-tablet-app-vineyard-grapes.webp","photoFocalY":0.41,"overlayId":42,"overlayUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/dashboard-spraying-conditions.webp","mobileStack":"text-first"} /-->
<!-- wp:cropx/two-column-overlay {"photoPosition":"left","heading":"Perform Deeper Analysis","body":"With curated field data, histograms and statistics, you'll be able to quickly see direct insight into a variety of information about your fields: soil type, NDVI, SAVI, soil moisture index, and more.","photoId":523,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-orchard-disease-spraying-scaled.webp","photoFocalY":0.41,"overlayId":42,"overlayUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/dashboard-spraying-conditions.webp","mobileStack":"text-first"} /-->
<!-- wp:cropx/testimonial-single {"quote":"I've tested nearly every soil moisture sensor on the market, and I've never been impressed. This year, I decided to give CropX a try after a conversation at Commodity Classic. The sensors were easy to install, and the integration with the John Deere Operations Center was seamless. The CropX system saved me eight full irrigation cycles on a remote farm 40 miles from home.","authorName":"Kevin Matthews","authorTitle":"Award-Winning Commodity Grower in North Carolina","showPhoto":false} /-->
<!-- wp:cropx/two-column {"heading":"Research \u0026amp; Validation","photoId":572,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-sand-county-foundation-samuel-agronomist-installing-sensor-scaled.webp","showIcon":false,"showEyebrow":false} -->
<!-- wp:paragraph {"placeholder":"Body text…"} -->
<p>The CropX system has undergone many internal and third-party trials and testing to validate the accuracy of the data it collects and the advice it provides. For data that comes from third-party providers, such as satellite images and weather forecasts, we choose high-caliber partners who are leaders in their fields of expertise. But sometimes situations arise where there are discrepancies in the data that need attention – and for that, our service and support teams are on-call to problem solve and make any necessary corrections. With CropX, you can trust that the data you receive is accurate and precise and that any questions you have will be answered.</p>
<!-- /wp:paragraph -->
<!-- /wp:cropx/two-column -->
<!-- wp:cropx/cards {"heading":"Real Results","queryMode":"auto","queryPostType":"post","bgColor":"deep-blue"} /-->
<!-- wp:cropx/pre-footer-cta {"backgroundImageId":585,"backgroundImageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-smart-farming-new-zealand-aerial-view.webp","eyebrowColor":"white"} /-->
