<?php
/**
 * Title: Segment — Service Provider
 * Slug: cropx/page-segment-service-provider
 * Categories: cropx-pages
 * Inserter: true
 */
?>
<!-- wp:cropx/hero-curved {"segment":"service-provider","bgImageId":548,"bgImageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-precision-farming-technology-agronomic-advisor.webp","bgFocalY":0.63,"bgZoom":114} /-->
<?php
$_seg_ref = cropx_get_synced_block_ref( 'segment-navigation' );
if ( $_seg_ref ) : ?>
<!-- wp:block {"ref":<?php echo $_seg_ref; ?>} /-->
<?php endif; ?>
<!-- wp:cropx/hardware-lineup {"eyebrowColor":"deep-blue","items":[{"name":"Vertex 4","description":"All-in-one smart soil sensor","url":"#","imageId":65,"imageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/vertex-tiny.webp","imageHeight":90,"thumbCentered":false},{"name":"Evato 1","description":"Actual ET sensor","url":"#","imageId":59,"imageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/evato-tiny.webp","imageHeight":100,"thumbCentered":false},{"name":"Strato 1","description":"All-in-one weather station","url":"#","imageId":62,"imageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/strato-tiny.webp","imageHeight":90,"thumbCentered":false},{"name":"Rivo 1","description":"Rain gauge","url":"#","imageId":61,"imageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/rivo-tiny.webp","imageHeight":72,"thumbCentered":true},{"name":"Telemetry 2","description":"Field data gateway","url":"#","imageId":63,"imageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/telemetry-tiny.webp","imageHeight":90,"thumbCentered":false},{"name":"Apex 1","description":"Precision soil sensor","url":"#","imageId":58,"imageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/apex-tiny.webp","imageHeight":95,"thumbCentered":false}],"bgColor":"white","sectionSeparator":"none"} /-->
<!-- wp:cropx/two-column-overlay {"segmentAccent":"service-provider","eyebrow":"THE CROPX PLATFORM","heading":"One Platform, Complete Farm Intelligence","body":"Manage unlimited farms from one intuitive dashboard. Our platform synthesizes soil sensors, satellite imagery, weather data, and machinery information into actionable insights for irrigation, nutrition, and disease management—delivering up to 50% water savings and 20% fertilizer reductions.","photoId":420,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-agricultural-technology-corn-field-golden-hour.webp","overlayId":42,"overlayUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/dashboard-spraying-conditions.webp","eyebrowColor":"deep-blue","bgColor":"white","sectionSeparator":"both"} /-->
<!-- wp:cropx/feature-stat {"photoPosition":"left","segmentAccent":"service-provider","icon":"speed","eyebrow":"GLOBAL PARTNER NETWORK","heading":"Grow Your Business with CropX","body":"Join our global partner network and offer farmers cutting-edge soil and crop intelligence. Access advanced agronomic tools, comprehensive training, and dedicated support while expanding your business with precision farming solutions that drive sustainable agriculture and revenue growth.","ctaLabel":"See how it works","photoId":436,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-agronomist-farmer-field-greens-vegetables.webp","cardContext":"Growers reduced water use by","eyebrowColor":"deep-blue","sectionSeparator":"line"} /-->
<!-- wp:cropx/two-column {"segmentAccent":"service-provider","icon":"antenna","heading":"Your Complete Field Intelligence Hardware Suite","body":"Capture comprehensive field data with our patented sensor suite: soil moisture and temperature monitoring, actual evapotranspiration measurement, rainfall tracking, and hyper-local weather data. Easy-to-install, accurate devices provide real-time insights that prevent crop stress before it starts.","photoId":446,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-agronomy-machinery-connections-tablet-2.webp","eyebrowColor":"deep-blue","ctaStyle":"link","bgColor":"white","sectionSeparator":"line"} /-->
<!-- wp:cropx/testimonial-single {"backgroundVariant":"blue","quote":"I've tested nearly every soil moisture sensor on the market, and I've never been impressed. This year, I decided to give CropX a try after a conversation at Commodity Classic. The sensors were easy to install, and the integration with the John Deere Operations Center was seamless. The CropX system saved me eight full irrigation cycles on a remote farm 40 miles from home.","authorName":"Kevin Matthews","authorTitle":"Award-Winning Commodity Grower in North Carolina","photoId":758,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/Kevin-M-Photo.png"} /-->
<!-- wp:cropx/stats-grid {"segmentAccent":"service-provider","stat4Number":"2K+","eyebrowColor":"deep-blue","bgColor":"white"} /-->
<!-- wp:cropx/cards {"cardVariant":"dark","cards":[{"photoId":493,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-farm-technology-corn-harvest-scaled.webp","photoAlt":"","tag":"Case Study","tagUrl":"#","date":"","title":"Case Study: Corn","excerpt":"This is an excerpt from the blog post","ctaLabel":"Read more","ctaUrl":"#"},{"photoId":428,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-agriculture-digital-platform-apple-orchard.webp","photoAlt":"","tag":"Case Study","tagUrl":"#","date":"","title":"Case Study: Apples","excerpt":"This is an excerpt from the blog post","ctaLabel":"Read more","ctaUrl":"#"},{"photoId":461,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-cotton-field-smart-farming.webp","photoAlt":"","tag":"Case Study","tagUrl":"#","date":"","title":"Case Study: Cotton","excerpt":"This is an excerpt from the blog post","ctaLabel":"Read more","ctaUrl":"#"}],"sectionSeparator":"both"} /-->
<!-- wp:cropx/faq-accordion {"heading":"FAQ Section","items":[{"question":"This is an FAQ Question","answer":"This is an FAQ Answer"},{"question":"This is an FAQ Question","answer":"This is an FAQ Answer"},{"question":"This is an FAQ Question","answer":"This is an FAQ Answer"}],"sectionSeparator":"both"} /-->
<!-- wp:cropx/pre-footer-cta {"heading":"CropX Service Providers temporibus autem quibusdam et aut officiis","subtext":"CropX temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet.","primaryLabel":"Let's Talk ROI","backgroundImageId":443,"backgroundImageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-agronomy-advisor-harvest-machinery-connections-laptop.webp","segmentAccent":"service-provider","eyebrowColor":"white"} /-->
