<?php
/**
 * Title: Segment — On-Farm
 * Slug: cropx/page-segment-on-farm
 * Categories: cropx-pages
 * Inserter: true
 */
?>
<!-- wp:cropx/hero-curved {"segment":"on-farm","bgImageId":441,"bgImageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-agronomoist-coffee-plantation.webp"} /-->
<?php
$_seg_ref = cropx_get_synced_block_ref( 'segment-navigation' );
if ( $_seg_ref ) : ?>
<!-- wp:block {"ref":<?php echo $_seg_ref; ?>} /-->
<?php endif; ?>
<!-- wp:cropx/hardware-lineup {"eyebrowColor":"deep-blue","items":[{"name":"Vertex 4","description":"All-in-one smart soil sensor","url":"#","imageId":65,"imageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/vertex-tiny.webp","imageHeight":90,"thumbCentered":false},{"name":"Evato 1","description":"Actual ET sensor","url":"#","imageId":59,"imageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/evato-tiny.webp","imageHeight":100,"thumbCentered":false},{"name":"Strato 1","description":"All-in-one weather station","url":"#","imageId":62,"imageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/strato-tiny.webp","imageHeight":90,"thumbCentered":false},{"name":"Rivo 1","description":"Rain gauge","url":"#","imageId":61,"imageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/rivo-tiny.webp","imageHeight":72,"thumbCentered":true},{"name":"Telemetry 2","description":"Field data gateway","url":"#","imageId":63,"imageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/telemetry-tiny.webp","imageHeight":90,"thumbCentered":false},{"name":"Apex 1","description":"Precision soil sensor","url":"#","imageId":58,"imageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/apex-tiny.webp","imageHeight":95,"thumbCentered":false}],"bgColor":"white","sectionSeparator":"none"} /-->
<!-- wp:cropx/two-column-overlay {"segmentAccent":"on-farm","icon":"field-sun","eyebrow":"THE CROPX Platform","heading":"One Platform, Complete Farm Intelligence","body":"Manage unlimited farms from one intuitive dashboard. Our platform synthesizes soil sensors, satellite imagery, weather data, and machinery information into actionable insights for irrigation, nutrition, and disease management—delivering up to 50% water savings and 20% fertilizer reductions.","ctaLabel":"See how it works","photoId":415,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-agricultural-technology-cattle-farmland-golden-hour.webp","overlayId":42,"overlayUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/dashboard-spraying-conditions.webp","eyebrowColor":"deep-blue","ctaStyle":"link","bgColor":"white","sectionSeparator":"both"} /-->
<!-- wp:cropx/two-column-overlay {"photoPosition":"left","segmentAccent":"on-farm","icon":"sensor-cloud","eyebrow":"CROPX HARDWARE OFFERINGS","heading":"Your Complete Field Intelligence Hardware Suite","body":"Capture comprehensive field data with our patented sensor suite: soil moisture and temperature monitoring, actual evapotranspiration measurement, rainfall tracking, and hyper-local weather data. Easy-to-install, accurate devices provide real-time insights that prevent crop stress before it start.","ctaLabel":"See how it works","photoId":514,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-grain-field-agronomic-technology-harvest-bales.webp","overlayId":42,"overlayUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/05/dashboard-spraying-conditions.webp","eyebrowColor":"deep-blue","ctaStyle":"link","bgColor":"white","sectionSeparator":"line"} /-->
<!-- wp:cropx/feature-stat {"segmentAccent":"on-farm","eyebrow":"REAL RESULTS","heading":"Optimize Yields, Resources, and Sustainability","body":"Optimize every aspect of your operation with our complete digital agronomy platform. Save on water, nutrients, and energy while increasing yields through real-time crop monitoring, precision irrigation, and disease risk management—all with seamless equipment integration and enterprise-grade tools.","ctaLabel":"View case studies","photoId":491,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-farm-management-farmer-tablet-tractor.webp","cardContext":"California citrus growers achieved a","cardNumber":"15%","cardMetric":"yield increase using the cropx system","eyebrowColor":"deep-blue","sectionSeparator":"line"} /-->
<!-- wp:cropx/testimonial-single {"backgroundVariant":"blue","quote":"I've tested nearly every soil moisture sensor on the market, and I've never been impressed. This year, I decided to give CropX a try after a conversation at Commodity Classic. The sensors were easy to install, and the integration with the John Deere Operations Center was seamless. The CropX system saved me eight full irrigation cycles on a remote farm 40 miles from home.","authorName":"Kevin Matthews","authorTitle":"Award-Winning Commodity Grower in North Carolina","photoId":758,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/Kevin-M-Photo.png"} /-->
<!-- wp:cropx/two-column-alternating {"showIntro":true,"introHeading":"CropX is compatible with all crops","introBody":"Don't see your crop here? Chances are it's still supported by the CropX system.","introCtaLabel":"Contact us to learn more","rows":[{"heading":"Vegetables &amp; Row Crops","body":"Artichoke · Asparagus · Beans · Beet · Broccoli · Cauliflower · Celery · Chickpeas · Cucumber · Eggplant · Endive · Garlic · Lettuce · Melon · Leek · Onion · Pepper · Potato · Radish · Spinach · Squash · Tomato · Watermelon · &amp; More","photoId":539,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-precision-crop-technology-potato-harvest-scaled.webp","photoAlt":""},{"heading":"Fruits &amp; Tree Nuts","body":"Almond · Apple · Avocado · Banana · Blackberry · Blueberry · Cacao · Cashew · Citrus · Cherry · Coffee · Fig · Grape · Kiwi · Mango · Peach · Pear · Pecan · Persimmon · Pistachio · Pomegranate · Raspberry · Strawberry · Walnut · &amp; More","photoId":624,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-technology-ripening-grapes.webp","photoAlt":""},{"heading":"Grains &amp; Commodity Crops","body":"Alfalfa · Barley · Canola · Cotton · Flaxseed · Hemp · Millet · Mustard Seed · Oats · Peanuts · Quinoa · Rapeseed · Range Grasses · Rice · Rye · Safflower Sorghum · Soybeans · Sugar Beets · Sunflowers · Tobacco · Wheat · &amp; More","photoId":461,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-cotton-field-smart-farming.webp","photoAlt":""},{"heading":"Other Specialty Crops","body":"Cilantro · Dill · Fennel · Ginger · Hops · Lavender · Mint · Parsley · Rocket · Tea Leaves · Tulips · Cut Flowers · Christmas Trees · Timber Trees · &amp; More","photoId":627,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-tulip-flower-field.webp","photoAlt":""}],"bgColor":"white"} /-->
<!-- wp:cropx/cards {"cardVariant":"dark","heading":"Proven Results with the CropX System","cards":[{"photoId":525,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-orchard-pear-agriculture.webp","photoAlt":"","tag":"Case Study","tagUrl":"#","date":"","title":"Case Study: Pears","excerpt":"This is an excerpt from the blog post","ctaLabel":"Read more","ctaUrl":"#"},{"photoId":626,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-tree-nuts-pecan-orchard.webp","photoAlt":"","tag":"Case Study","tagUrl":"#","date":"","title":"Case Study: Pecans","excerpt":"This is an excerpt from the blog post","ctaLabel":"Read more","ctaUrl":"#"},{"photoId":625,"photoUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-tomato-plants-irrigation.webp","photoAlt":"","tag":"Case Study","tagUrl":"#","date":"","title":"Case Study: Tomatoes","excerpt":"This is an excerpt from the blog post","ctaLabel":"Read more","ctaUrl":"#"}],"sectionSeparator":"both"} /-->
<!-- wp:cropx/stats-grid {"segmentAccent":"on-farm","stat4Number":"2K+","eyebrowColor":"deep-blue","bgColor":"white","sectionSeparator":"both"} /-->
<!-- wp:cropx/faq-accordion {"heading":"FAQ Section","items":[{"question":"This is an FAQ Question","answer":"This is an FAQ Answer"},{"question":"This is an FAQ Question","answer":"This is an FAQ Answer"},{"question":"This is an FAQ Question","answer":"This is an FAQ Answer"}],"sectionSeparator":"both"} /-->
<!-- wp:cropx/pre-footer-cta {"heading":"One connected system. Smarter decisions. Stronger results.","subtext":"CropX temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet","primaryLabel":"Let's Talk ROI","backgroundImageId":590,"backgroundImageUrl":"http://ec2-100-25-145-190.compute-1.amazonaws.com/wp-content/uploads/2026/06/cropx-soil-health-monitoring-technology.webp","segmentAccent":"on-farm","eyebrowColor":"white"} /-->
