<?php
/**
 * Small accessibility patches for third-party plugin markup we don't control.
 *
 * PageSpeed Insights flagged two elements with no accessible name:
 *   1. The Simple Commenter comment-form status checkbox
 *      (input.simple-commenter-status-checkbox) — no associated <label>.
 *   2. The Complianz cookie-statement link (a.cmplz-link.cookie-statement)
 *      — renders with no visible/accessible link text in our theme's markup.
 *
 * Both are generated by plugins, not our theme templates, so there's no
 * render.php or template part to edit directly. Rather than forking or
 * hacking the plugins, a tiny footer script patches in the missing
 * aria-label after the page loads. This is purely additive — it never
 * changes what's visually on the page, only what screen readers announce.
 *
 * No build step needed: this is a plain inline script via wp_footer, not
 * part of the webpack/block asset pipeline.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

add_action( 'wp_footer', function () {
	?>
	<script>
	document.addEventListener( 'DOMContentLoaded', function () {
		// 1. Simple Commenter status checkbox(es) — no associated label.
		document.querySelectorAll( 'input.simple-commenter-status-checkbox:not([aria-label])' ).forEach( function ( el ) {
			el.setAttribute( 'aria-label', 'Remember my name and email for next time' );
		} );

		// 2. Complianz cookie-statement link — no discernible link text.
		document.querySelectorAll( 'a.cmplz-link.cookie-statement:not([aria-label])' ).forEach( function ( el ) {
			if ( ! el.textContent.trim() ) {
				el.setAttribute( 'aria-label', 'Cookie statement' );
			}
		} );
	} );
	</script>
	<?php
}, 20 );
