<?php
/**
 * Title: Segment — Enterprise
 * Slug: cropx/page-segment-enterprise
 * Categories: cropx-pages
 * Inserter: true
 */
?>
<!-- wp:cropx/segment-hero {"heading":"Your <em>one-stop solution</em> for traceability &amp; compliance","subheading":"Streamline sustainability reporting and achieve compliance while driving measurable impact through intelligent data management.","bgImageId":310,"bgImageUrl":"http://cropx-2026-2.local/wp-content/uploads/2026/06/cropx-agronomy-machinery-connections-tablet-2.webp"} /-->
<!-- wp:cropx/segments /-->
<!-- wp:cropx/logo-strip /-->
<!-- wp:cropx/two-column-overlay {"segmentAccent":"enterprise","icon":"field-sun","eyebrow":"TRACEABILITY &amp; COMPLIANCE","heading":"Sustainability You Can Actually Measure","body":"Track sustainability metrics and streamline compliance across your entire agricultural supply chain. Our digital platform collects verified field-level data, calculates emissions, manages certifications, and creates audit-ready reports—transforming complex sustainability management into clear, measurable results.","ctaLabel":"See how it works","photoId":267,"photoUrl":"http://cropx-2026-2.local/wp-content/uploads/2026/06/cropx-precision-ag-field-monitoring-tea-plantation.webp","overlayId":42,"overlayUrl":"http://cropx-2026-2.local/wp-content/uploads/2026/05/dashboard-spraying-conditions.webp","eyebrowColor":"deep-blue","ctaStyle":"link"} /-->
<!-- wp:cropx/two-column-overlay {"photoPosition":"left","segmentAccent":"enterprise","icon":"speed","eyebrow":"CENTRALIZED FIELD &amp; CROP DATA","heading":"Centralize Data and Grow Smarter with FarmLook","body":"Centralize field and crop data across your grower network with secure, standardized data exchange. Track cultivation progress, manage contracts, forecast yields, and integrate seamlessly with your ERP systems—all while giving growers control of their data through customizable service levels.","ctaLabel":"See how it works","photoId":225,"photoUrl":"http://cropx-2026-2.local/wp-content/uploads/2026/06/cropx-harvest-supply-chain-truck-transport.webp","overlayId":42,"overlayUrl":"http://cropx-2026-2.local/wp-content/uploads/2026/05/dashboard-spraying-conditions.webp","eyebrowColor":"deep-blue","ctaStyle":"link"} /-->
<!-- wp:cropx/two-column {"segmentAccent":"enterprise","icon":"language","eyebrow":"THE CROPX API","heading":"Your Complete Field Intelligence Hardware Suite","body":"Integrate comprehensive agricultural data into your digital products through our custom API. Access soil-to-satellite insights, AI-enhanced analytics, and agronomic advice without building from scratch. Pull only the data and visualizations you need to enhance your offering quickly.","photoId":206,"photoUrl":"http://cropx-2026-2.local/wp-content/uploads/2026/06/cropx-engineering-team-office-development.webp","eyebrowColor":"deep-blue","ctaStyle":"link"} /-->
<!-- wp:cropx/testimonial-single {"backgroundVariant":"blue","quote":"Expanding our relationship with CropX is a critical next step in our ongoing mission to ensure sustainable cocoa systems to cooperatives and farmers. CropX technology gives us more visibility into growers' sustainability practices and how our cocoa is being produced. This helps us improve EUDR compliance, but also enhance collaboration with growers for stronger sustainable outcomes.","authorName":"Elizabeth Rizo","authorTitle":"Cocoa Cooperation and Purchasing Manager","authorCompany":"Ritter Sport","photoId":30,"photoUrl":"http://cropx-2026-2.local/wp-content/uploads/2026/05/wide-farm-landscape.webp"} /-->
<!-- wp:cropx/stats-grid {"segmentAccent":"enterprise","stat4Number":"2K+","eyebrowColor":"deep-blue"} /-->
<!-- wp:separator {"className":"is-style-wide","style":{"color":{"background":"#e3e3e3"}}} -->
<hr class="wp-block-separator has-text-color has-alpha-channel-opacity has-background is-style-wide" style="background-color:#e3e3e3;color:#e3e3e3"/>
<!-- /wp:separator -->
<!-- wp:cropx/cards {"cardVariant":"dark","heading":"Proven Results with the CropX System","cards":[{"photoId":287,"photoUrl":"http://cropx-2026-2.local/wp-content/uploads/2026/06/cropx-supply-chain-food-juice-production.webp","photoAlt":"","tag":"Case Study","tagUrl":"#","date":"","title":"Case Study: Citrus","excerpt":"This is an excerpt from the blog post","ctaLabel":"Read more","ctaUrl":"#"},{"photoId":292,"photoUrl":"http://cropx-2026-2.local/wp-content/uploads/2026/06/cropx-agriculture-wheat-field-plants-mature.webp","photoAlt":"","tag":"Case Study","tagUrl":"#","date":"","title":"Case Study: Wheat","excerpt":"This is an excerpt from the blog post","ctaLabel":"Read more","ctaUrl":"#"},{"photoId":261,"photoUrl":"http://cropx-2026-2.local/wp-content/uploads/2026/06/cropx-smart-farming-cattle-new-zealand.webp","photoAlt":"","tag":"Case Study","tagUrl":"#","date":"","title":"Case Study: Dairy","excerpt":"This is an excerpt from the blog post","ctaLabel":"Read more","ctaUrl":"#"}]} /-->
<!-- wp:separator {"className":"is-style-wide","style":{"color":{"background":"#e3e3e3"}}} -->
<hr class="wp-block-separator has-text-color has-alpha-channel-opacity has-background is-style-wide" style="background-color:#e3e3e3;color:#e3e3e3"/>
<!-- /wp:separator -->
<!-- wp:cropx/faq-accordion {"heading":"FAQ Section","items":[{"question":"This is an FAQ Question","answer":"This is an FAQ Answer"},{"question":"This is an FAQ Question","answer":"This is an FAQ Answer"},{"question":"This is an FAQ Question","answer":"This is an FAQ Answer"}]} /-->
<!-- wp:cropx/pre-footer-cta {"heading":"Power your traceability &amp; compliance initiatives with CropX","backgroundImageId":324,"backgroundImageUrl":"http://cropx-2026-2.local/wp-content/uploads/2026/06/cropx-netherlands-cattle-europe-potatoes.webp","segmentAccent":"enterprise","eyebrowColor":"white"} /-->
<!-- wp:cropx/footer /-->
